language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.6.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
        - pip3 install pytest
        - cd context_menu/tests
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: "Python 3.7.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
        - pip3 install pytest
        - cd context_menu/tests
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip3 install pytest
        - cd context_menu/tests
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
script: pytest
